Ensure build is .
AnacondaRecipes/libzip-feedstock pull request #3
Opened 2022-03-25 17:36 UTC by ScottBailey

Correct cmake files.

2022-03-28 13:58 UTC, tobijk approved these changes
LGTM

2022-05-05 20:36 UTC, cbouss requested changes
I think it we would be good to add tests to check for headers in the package:
- test -f ${PREFIX}/include/zip.h  # [linux or osx]
- test -f ${PREFIX}/include/zipconf.h  # [linux or osx]
- if not exist %LIBRARY_BIN%\\include\\zip.h exit 1  # [win]
- if not exist %LIBRARY_BIN%\\include\\zipconf.h exit 1  # [win]

2022-05-05 21:19 UTC, cbouss approved these changes
LGTM

2022-05-05 22:08 UTC, cbouss approved these changes

2022-05-05 22:18 UTC, merged